version = "3.7.17"
runner.dialect = scala213

maxColumn = 120
assumeStandardLibraryStripMargin = true
align.preset = more
align.multiline = false

continuationIndent {
  defnSite = 2
  callSite = 2
}

newlines {
  beforeCurlyLambdaParams = multilineWithCaseOnly
  afterCurlyLambdaParams = squash
}

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]

rewrite.redundantBraces.stringInterpolation = true
